version: "3"
services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - course_service

  user_service:
    build: ./user-service
    ports:
      - "8001:8001"

  course_service:
    build: ./course-service
    ports:
      - "8002:8002"
