version: "3"
services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - course-service
      - learner-service
      - payment-service

  user-service:
    build: ./user-service
    ports:
      - "31001:8001"

  course-service:
    build: ./course-service
    ports:
      - "31003:8003"

  learner-service:
    build: ./learner-service
    ports:
      - "31004:8004"

  payment-service:
    build: ./payment-service
    ports:
      - "31005:8005"
