version: "3"
services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - course-service
      - learner-service
      - payment-service

  user-service:
    build: ./user-service
    ports:
      - "8001:8001"

  course-service:
    build: ./course-service
    ports:
      - "8003:8003"

  learner-service:
    build: ./learner-service
    ports:
      - "8004:8004"

  payment-service:
    build: ./payment-service
    ports:
      - "8005:8005"
