apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service-app
  labels:
    app: course-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service-app
  template:
    metadata:
      labels:
        app: course-service-app
    spec:
      containers:
        - name: course-service-app
          image: anojpeiris/course-service:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8003

---
apiVersion: v1
kind: Service
metadata:
  name: course-service-svc
spec:
  selector:
    app: course-service-app
  ports:
    - port: 80
      targetPort: 8003
