apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server-app
  labels:
    app: user-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server-app
  template:
    metadata:
      labels:
        app: user-server-app
    spec:
      containers:
        - name: user-server-app
          image: anojpeiris/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: user-server-svc
spec:
  selector:
    app: user-server-app
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001 # Specify your desired NodePort here
      protocol: TCP
