apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-server-app
  labels:
    app: course-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-server-app
  template:
    metadata:
      labels:
        app: course-server-app
    spec:
      containers:
        - name: course-server-app
          image: anojpeiris/course-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003

---
apiVersion: v1
kind: Service
metadata:
  name: course-server-svc
spec:
  selector:
    app: course-server-app
  type: NodePort
  ports:
    - port: 8003
      targetPort: 8003
      nodePort: 30003 # Specify your desired NodePort here
      protocol: TCP
