apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course-service
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8003 #to communicate couple of pods
      targetPort: 8003
      nodePort: 30033
  type: LoadBalancer
  # type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service # name of the deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service #same name as server app name ,name for the selector for the pod
    spec:
      containers:
        - name: demoserver
          image: anojpeiris/demoserver:v1.0.0
          ports:
            - containerPort: 8080
